api:
  id: 11965840
  hash: "716c845bdc09adf2b6db0b63e4a455"
  bot_token: "6998765478:AAF-bWsygAmJQpUKSCgINRhs7wOAeYG9fiQ"

bot:
  name: "my_bot"

messages:
  welcome: "Welcome! 🎓 I'm here to help with your advanced studies."
  papers_prompt: "Select a subject:"